[server]
# 开启无头模式，减少后台干扰
headless = true
# 关闭 CORS 检查，加快连接握手速度
enableCORS = false
# 关闭 XSRF 保护 (内网/个人使用可以关掉以提速)
enableXsrfProtection = false

[browser]
#以此减少不必要的弹窗和收集
gatherUsageStats = false
# 让浏览器缓存静态资源，第二次打开会变快
serverAddress = "localhost"

[runner]
# 开启快速重运行模式
fastReruns = true
